### ISSUE TITLE
Version Conserns 

### ISSUE THREAD

**Issue by kevinwaxi** [navariltd/CSF_KE#55]
If installing this will still work on versions earlier let's say version 13. I tried to install version 13 in my local dev, but it is still not successful. The reason I am asking about this is that I have a client running version 13 in production but does not want the update, how would you tackle such situation

**Comment by muchai** [comment]
You can fork the app, and downgrade your branch. Also, best to try convince your customer to upgrade. V13 is no longer supported by Frappe since Jan 1.
