### ISSUE TITLE
Error while trying to open Kenya Sales Tax Report

### ISSUE THREAD

**Issue by ramanduck** [navariltd/CSF_KE#79]
Getting an error while trying to open Kenya Sales Tax Report:

```
pymysql.err.OperationalError: (1054, "Unknown column 'tabSales Invoice.etr_serial_number' in 'field list'")
Possible source of error: csf_ke (app)
```

<img width="838" alt="Screenshot 2024-07-27 at 3 22 52 PM" src="https://github.com/user-attachments/assets/861fa17c-25e7-4cdf-825a-e461bef53377">

**Comment by maniamartial** [comment]
Try running migrations, we have a patch that needs to run and create those 'etr' fields in the sales invoice doctype. 

![Screenshot from 2024-07-27 17-44-41](https://github.com/user-attachments/assets/9d5f0a71-795d-4b64-bab5-8efed603f013)
![Screenshot from 2024-07-27 17-45-26](https://github.com/user-attachments/assets/cad644e5-2b39-4e6a-8e70-cb58f3882461)


If the issue persists, use version-15 or version-14 as we check on this(we have changes we are still fixing on our develop branch)
Thank you.

**Comment by ramanduck** [comment]
I am using frappecloud. How to run the migrations there?
I am already on version-15

**Comment by maniamartial** [comment]
Navigate to your site, click on tab Actions
Below you'll see Migrate button

See in the image below
![image](https://github.com/user-attachments/assets/2eb74e7d-05a6-4672-863e-28abc32cc88b)

**Comment by ramanduck** [comment]
Same error even after running migrate

<img width="952" alt="Screenshot 2024-08-02 at 3 53 41 PM" src="https://github.com/user-attachments/assets/cd7c9a44-911e-450a-bfcf-4e9eddf1c31c">


<img width="797" alt="Screenshot 2024-08-02 at 3 50 27 PM" src="https://github.com/user-attachments/assets/e4775f1d-7c00-4756-ac29-de5c86b3b72f">

**Comment by ramanduck** [comment]
Any update?

**Comment by maniamartial** [comment]
@ramanduck Still looking into the issue, we've noticed all the patches are not being executed. Will get back

**Comment by maniamartial** [comment]
Hello @ramanduck , this has been resolved. Will close the issue soon once we merge in version-15, currently working fine on develop.

**Comment by maniamartial** [comment]
I am marking this as solved, and closing the issue.
